import { Link } from "react-router-dom";

const PROJECTS = [
  {
    id: "RP-001",
    title: "Nsukka UTI Ethnobotany & Antimicrobial Validation",
    status: "Ongoing",
    stage: "Protocol development · ethics preparation · field readiness",
    location: "Nsukka Educational Zone, Enugu State, Nigeria",
    summary:
      "A field-to-laboratory study documenting herbal remedies used for urinary tract infection and frequent urination, authenticating voucher specimens, and scientifically prioritising selected plants for antibacterial validation.",
    pillars: [
      "Ethnobotanical field survey and traditional-knowledge documentation",
      "Voucher specimens, botanical authentication and photo records",
      "RFC, Use Value, Fidelity Level and informant-consensus analysis",
      "Laboratory antibacterial screening with MIC/MBC confirmation",
      "Phytochemical, safety and translational prioritisation",
    ],
    outputs: "Voucher-authenticated dataset · laboratory evidence · manuscripts · preliminary data for international AMR/natural-product grants",
    relationship: "First NigerFlora field-to-laboratory research project and an evidence-generating pilot for NEXUS-AMR Africa.",
  },
  {
    id: "RP-002",
    title: "NEXUS-AMR Africa",
    status: "Ongoing",
    stage: "Consortium development · institutional engagement · international grant preparation",
    location: "Proposed hub: University of Nigeria, Nsukka",
    summary:
      "A flagship One Health research and innovation programme connecting antimicrobial-resistance surveillance, pathogen genomics, climate/environment intelligence, antimicrobial discovery, implementation research and African research-capacity development.",
    pillars: [
      "One Health AMR surveillance across human, animal and environmental systems",
      "Genomics and molecular epidemiology",
      "Climate-AMR and geospatial risk intelligence",
      "African natural-product antimicrobial discovery",
      "Implementation science, health economics and policy translation",
    ],
    outputs: "International consortium · reusable surveillance/data infrastructure · trained researchers · intervention evidence · translational research pipeline",
    relationship: "The programme is designed to absorb validated preliminary evidence and research infrastructure generated by focused pilot studies such as RP-001.",
  },
];

export default function ResearchProjects() {
  return (
    <div className="min-h-screen bg-cream">
      <nav className="sticky top-0 z-50 flex items-center justify-between bg-forest-700 px-5 py-4 text-white shadow-md md:px-8">
        <Link to="/" className="flex items-center gap-2.5">
          <span className="text-2xl">🌿</span>
          <div>
            <div className="text-lg font-bold text-gold-300">NigerFlora BioSciences</div>
            <div className="hidden text-xs text-forest-200 sm:block">Care · Research · Discovery</div>
          </div>
        </Link>
        <div className="flex items-center gap-2">
          <Link to="/" className="rounded-md px-3 py-2 text-sm text-forest-100 hover:bg-forest-600">Home</Link>
          <Link to="/formulary" className="hidden rounded-md px-3 py-2 text-sm text-forest-100 hover:bg-forest-600 sm:block">Formulary</Link>
          <Link to="/bioinformatics-services" className="hidden rounded-md px-3 py-2 text-sm text-forest-100 hover:bg-forest-600 md:block">Research Services</Link>
          <Link to="/register" className="btn-secondary px-4 py-2 text-sm">Researcher Account</Link>
        </div>
      </nav>

      <section className="bg-forest-900 text-white">
        <div className="mx-auto max-w-7xl px-6 py-16 md:py-20">
          <div className="max-w-4xl">
            <div className="inline-flex rounded-full bg-gold-300/15 px-4 py-2 text-xs font-bold uppercase tracking-[0.2em] text-gold-300">
              Active research portfolio
            </div>
            <h1 className="mt-5 text-4xl font-bold md:text-6xl">Ongoing research in Nsukka, AMR and translational natural-product science.</h1>
            <p className="mt-6 max-w-3xl text-lg leading-8 text-forest-100">
              NigerFlora research projects are structured as staged programmes with explicit scientific boundaries, ethics/governance gates and publication or grant-development outputs.
            </p>
          </div>
        </div>
      </section>

      <section className="mx-auto max-w-7xl px-6 py-12">
        <div className="grid gap-7 lg:grid-cols-2">
          {PROJECTS.map((project) => (
            <article key={project.id} className="overflow-hidden rounded-3xl border border-forest-100 bg-white shadow-sm">
              <div className="border-b border-forest-100 bg-forest-50 p-6">
                <div className="flex flex-wrap items-start justify-between gap-4">
                  <div>
                    <div className="text-xs font-bold uppercase tracking-[0.18em] text-forest-500">{project.id}</div>
                    <h2 className="mt-2 text-2xl font-bold text-forest-900">{project.title}</h2>
                  </div>
                  <span className="rounded-full bg-forest-700 px-3 py-1.5 text-xs font-bold text-white">{project.status}</span>
                </div>
                <div className="mt-4 text-sm font-semibold text-gold-700">{project.stage}</div>
                <div className="mt-1 text-sm text-gray-500">{project.location}</div>
              </div>

              <div className="space-y-6 p-6">
                <p className="text-sm leading-7 text-gray-600">{project.summary}</p>

                <div>
                  <h3 className="text-sm font-bold uppercase tracking-wide text-forest-700">Research pillars</h3>
                  <ul className="mt-3 space-y-2 text-sm leading-6 text-gray-600">
                    {project.pillars.map((pillar) => (
                      <li key={pillar} className="flex gap-2"><span className="text-gold-600">◆</span><span>{pillar}</span></li>
                    ))}
                  </ul>
                </div>

                <div className="rounded-2xl bg-cream p-4">
                  <div className="text-xs font-bold uppercase tracking-wide text-forest-600">Planned value</div>
                  <p className="mt-2 text-sm leading-6 text-gray-600">{project.outputs}</p>
                </div>

                <div className="border-l-2 border-gold-300 pl-4">
                  <div className="text-xs font-bold uppercase tracking-wide text-gold-700">Programme relationship</div>
                  <p className="mt-2 text-sm leading-6 text-gray-600">{project.relationship}</p>
                </div>
              </div>
            </article>
          ))}
        </div>
      </section>

      <section className="mx-auto max-w-7xl px-6 pb-16">
        <div className="rounded-3xl bg-forest-800 p-7 text-white md:p-10">
          <div className="grid gap-6 md:grid-cols-[1.2fr_0.8fr] md:items-center">
            <div>
              <h2 className="text-2xl font-bold">Research collaboration and consortium development</h2>
              <p className="mt-3 max-w-3xl text-sm leading-7 text-forest-100">
                Institutional, laboratory, genomics, pharmacognosy, public-health and translational collaborators may engage through controlled project-development workflows. Formal participation, access to unpublished data and use of project IP remain subject to appropriate agreements and approvals.
              </p>
            </div>
            <div className="flex flex-col gap-3 sm:flex-row md:justify-end">
              <Link to="/register" className="btn-secondary px-6 py-3 text-center">Create Researcher Account</Link>
              <Link to="/bioinformatics-services" className="btn-outline border-white px-6 py-3 text-center text-white hover:bg-white/10">Research Services</Link>
            </div>
          </div>
        </div>
      </section>

      <section className="mx-auto max-w-7xl px-6 pb-16">
        <div className="rounded-2xl border border-amber-100 bg-amber-50 p-5 text-sm leading-6 text-amber-900">
          <strong>Research-status notice:</strong> “Ongoing” describes active protocol, ethics, field/laboratory, consortium or grant-development work. It does not imply ethics approval, participant recruitment, external funding, clinical efficacy, regulatory approval or successful completion unless explicitly stated.
        </div>
      </section>

      <footer className="bg-forest-900 px-6 py-8 text-center text-sm text-forest-300">
        <div className="font-semibold text-gold-300">NigerFlora BioSciences</div>
        <p className="mt-2">Research projects are presented for scientific transparency and collaboration, not as therapeutic claims.</p>
      </footer>
    </div>
  );
}
